### ISSUE TITLE
Buttons do not work anymore

### ISSUE THREAD

**Issue by g-team23** [berrywhite96/lovelace-shutter-row#37]
The additional Button that can be configured, do not work anymore.
Maybe that has to do with the service/action changes recently in HomeAssistent!?

**Comment by berrywhite96** [comment]
Still works for me, can you share your card yaml?

**Comment by g-team23** [comment]
This is the yaml-code:

type: custom:shutter-row
move_up_button: {}
move_stop_button: {}
move_down_button: {}
entity: cover.rollo_gaestezimmer
name: Rollo Gästezimmer
preset_buttons:
  - name: Sonnenschutz
    icon: mdi:window-shutter
    tap_action:
      action: perform-action
      perform_action: automation.trigger
      target:
        entity_id: automation.rollo_gastezimmer_sonnenschutz
      data:
        skip_condition: true


Am So., 15. Sept. 2024 um 15:39 Uhr schrieb berrywhite96 <
***@***.***>:

**Comment by berrywhite96** [comment]
Oh I see you are right, seems like a bit of work to switch the action handling.

The example in the docs are still correct just the lovelace UI configurator generates wrong yaml code.
This should work:
```
preset_buttons:
  - name: Sonnenschutz
    icon: mdi:window-shutter
    tap_action:
      action: call-service
      service: automation.trigger
      data:
        entity_id: automation.rollo_gastezimmer_sonnenschutz
        skip_condition: true
```
