### ISSUE TITLE
Size of card

### ISSUE THREAD

**Issue by PierreScerri** [berrywhite96/lovelace-shutter-row#7]
I recently came across your shutter-row card.  It is what I have been looking for. Till now I was using a standard entity card followed by slider-entity-row like so:
```
type: entities
entities:
  - entity: cover.all_shutters
    secondary_info: last-changed
  - type: custom:slider-entity-row
    full_row: true
    entity: cover.all_shutters
```
giving:
<img width="449" alt="Screenshot 2022-09-07 at 12 14 07" src="https://user-images.githubusercontent.com/34303331/188853610-81b08275-3a69-40bf-a3c3-5ef4637ea1d2.png">
This works well but is more laborious to do for 15 shutters.

Now we come to your card.

I have defined the same shutter thus:

```
type: entities
entities:
  - type: custom:shutter-row
    entity: cover.all_shutters
state_color: true
show_header_toggle: false
```

or
```
square: false
columns: 1
type: grid
cards:
  - type: custom:shutter-row
    entity: cover.all_shutters
```

I have these issues
1.   Positions do not tally
2.  The height of your card is greater than the other 2 combined. This increases the overall size of the grid.  How can I reduce this?
3.  Cannot get the icon to change colour with state.
These issues are evident in the screenshot:

<img width="900" alt="Screenshot 2022-09-07 at 12 36 40" src="https://user-images.githubusercontent.com/34303331/188858076-eefdcb99-ee79-4ac5-929b-727bdccc0ae5.png">

Your comments would be most appreciated.

Thank you
